### PR TITLE
SPM integration

### PR DESCRIPTION
**Pull request by leszko11**
Hi guys!

I added SPM support to your library :)

### CODE REVIEW

**Comment by sandammeer** [comment]
Thank you for your contribution to this project - i will review your code tomorrow :)

**Comment by sandammeer** [comment]
I did some minor changes and updated the version to 0.5.0

**Comment by leszko11** [comment]
I should have also made some changes to README file. I can do that later this day

**Comment by leszko11** [comment]
Oh, you did. Nevermind 😅

**Pull request merged**
